### PR TITLE
fix apply new patch apk based on the working patch apk

### LINKED ISSUE #73: Apply a new patch APK based on the working patch apk would crash
Running host apk and apply a patch apk. Now running on the patch apk.  And when apply a newer patch apk, release process crashes.

### PR DESCRIPTION
**Pull request by peacepassion**
close #73   #79

Use checksum as dir name for each patch.

### CODE REVIEW

**Comment by peacepassion** [comment]
请耐心review，这个改动幅度略大！

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java [hunk 1]
```diff
@@ -51,52 +52,65 @@
...
             try {
-                ensureAmigoDirs();
+                Log.e(TAG, "working checksum: " + workingPatchApkChecksum);
+                ensureAmigoDirs(workingPatchApkChecksum);
                 if (checkUpgrade()) {
                     throw new RuntimeException("Host app has upgrade");
                 }
-                if (!patchApk.exists()) {
+                if (TextUtils.isEmpty(workingPatchApkChecksum) || !patchApks.exists(workingPatchApkChecksum)) {
                     throw new RuntimeException("Patch apk doesn't exists");
```
Comment (JackCho) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: 这种情况下也抛异常的话，对于amigo失败统计会造成影响的

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java [hunk 2]
```diff
@@ -51,52 +52,65 @@
...
                 }
-                if (!checkSignature()) {
+                if (!checkSignature(workingPatchApkChecksum)) {
                     throw new RuntimeException("Patch apk has illegal signature");
                 }
-                if (!checkVersion()) {
+                if (!checkVersion(workingPatchApkChecksum)) {
                     throw new RuntimeException("Patch apk version can't downgrade");
```
Comment (JackCho) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: may be deleted

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java [hunk 3]
```diff
@@ -163,25 +174,24 @@ private void releasePatchApk() throws Exception {
...
         }
         return false;
     }
 
-    private void ensureAmigoDirs() throws Exception {
-        AmigoDirs.init(this);
-        amigoDirs = AmigoDirs.getInstance();
-        patchApk = PatchApk.getInstance();
+    private void ensureAmigoDirs(String checksum) throws Exception {
+        amigoDirs = AmigoDirs.getInstance(this);
```
Comment (FtheGFW) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: checksum is not used ?

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java (hunk 2 above)
Comment (peacepassion) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: 恩，这个意义确实不大了，我来删吧

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java (hunk 3 above)
Comment (peacepassion) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: 恩，我改一下

**Comment by JackCho** [comment]
👍

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java [hunk 4]
```diff
@@ -163,25 +174,24 @@ private void releasePatchApk() throws Exception {
...
+            return amigoDirs.dexOptDir(checksum).listFiles().length > 0;
         }
         return false;
     }
 
-    private void ensureAmigoDirs() throws Exception {
-        AmigoDirs.init(this);
-        amigoDirs = AmigoDirs.getInstance();
-        patchApk = PatchApk.getInstance();
+    private void ensureAmigoDirs(String checksum) throws Exception {
```
Comment (2dxgujun) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: checksum is unused

File: amigo-lib/src/main/java/me/ele/amigo/AmigoDirs.java [hunk 5]
```diff
@@ -4,94 +4,139 @@
...
 
-    public File libDir() {
-        return libDir;
+    public File libDir(String checksum) {
+        ensurePatchDirs(checksum);
+        checkInitState(libDirs, checksum);
+        return libDirs.get(checksum);
+    }
+
+    private void checkInitState(Map<String, File> map, String checksum) {
```
Comment (FtheGFW) [inline amigo-lib/src/main/java/me/ele/amigo/AmigoDirs.java]: since #ensurePatchDirs would throw an exception if any error occurred during creating those files,  I don't think this check would be that necessary.

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java [hunk 6]
```diff
@@ -409,53 +412,58 @@ public static void work(Context context, File patchFile) {
...
+    private void clearWithoutPatch(String checksum) {
+        Log.e(TAG, "clear without patch");
+        File[] patchDirs = amigoDirs.amigoDir().listFiles();
+        if (patchDirs != null && patchDirs.length > 0) {
+            for (File patchDir : patchDirs) {
+                if (patchDir.getName().equals(checksum)) {
+                    File[] files = patchDir.listFiles();
+                    for (File file : files) {
+                        if (!file.getAbsolutePath().equals(patchApks.patchPath(checksum))) {
+                            Log.e(TAG, "remove file: " + file.getAbsolutePath());
```
Comment (FtheGFW) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: ?

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java [hunk 7]
```diff
@@ -51,52 +52,65 @@
...
-            if (!ProcessUtils.isMainProcess(this) && isPatchApkFirstRun()) {
+            if (!ProcessUtils.isMainProcess(this) && isPatchApkFirstRun(workingPatchApkChecksum)) {
                 Log.e(TAG, "None main process and patch apk is not released yet");
                 runOriginalApplication();
                 return;
             }
 
             // only release loaded apk in the main process
-            runPatchApk();
+            runPatchApk(workingPatchApkChecksum);
```
Comment (FtheGFW) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: when will you remove the old path files ?

Comment (peacepassion) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: old patches目前并没有专门删除。 目前只是在host升级和其他一些异常情况时，把所有patch相关东西全部删除.

File: amigo-lib/src/main/java/me/ele/amigo/AmigoDirs.java (hunk 5 above)
Comment (2dxgujun) [inline amigo-lib/src/main/java/me/ele/amigo/AmigoDirs.java]: +1

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java (hunk 6 above)
Comment (peacepassion) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: 你是说clearWithoutPatch的调用么？

File: amigo-lib/src/main/java/me/ele/amigo/AmigoDirs.java (hunk 5 above)
Comment (peacepassion) [inline amigo-lib/src/main/java/me/ele/amigo/AmigoDirs.java]: 对的，忘了删了

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java (hunk 6 above)
Comment (FtheGFW) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: I mean this :
!file.getAbsolutePath().equals(patchApks.patchPath(checksum))

Comment (peacepassion) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: 要的，这里是要保留apk，删除可能的残存的释放出的dex啥的

File: amigo-lib/src/main/java/me/ele/amigo/Amigo.java [hunk 8]
```diff
@@ -109,44 +121,42 @@ public void onCreate() {
...
             Method addAssetPath = getDeclaredMethod(AssetManager.class, "addAssetPath", String.class);
             addAssetPath.setAccessible(true);
-            addAssetPath.invoke(assetManager, patchApk.patchPath());
+            addAssetPath.invoke(assetManager, patchApks.patchPath(checksum));
             setAPKResources(assetManager);
 
             patchedClassLoader = amigoClassLoader;
+
+            sharedPref.edit().putString(WORKING_PATCH_APK_CHECKSUM, checksum).commit();
+            clearOldPatches(checksum);
```
Comment (peacepassion) [inline amigo-lib/src/main/java/me/ele/amigo/Amigo.java]: 修改了一下逻辑，在成功拉起新的patch apk后，把其他的patch files清掉 @FtheGFW

**Comment by FtheGFW** [comment]
👍
